name = "hatlocker"
description = "HatLocker"
version = "{{ version }}"
distro = "{{ distro }}"

[[packages]]
name = "tmux"

[[containers]]
source = "quay.io/fedora/fedora:latest"

[customizations.services]
enabled = []
disabled = []
masked = []

[customizations.timezone]
timezone = "Europe/Amsterdam"

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "us"

[customizations.firewall]
ports = []

[customizations.firewall.services]
enabled = []
disabled = []

[[customizations.repositories]]
id = "hatlocker"
name = "Hatlocker"
baseurls = ["{{ repo_url }}"]
gpgcheck = true
gpgkeys = ["{{ repo_key_url }}"]
enabled = true
